// Generated by matugen — do not edit
import QtQuick

QtObject {
    readonly property color background:  "#333340"
    readonly property color surface:     "#3e3e4a"
    readonly property color surfaceHigh: "#474751"
    readonly property color fg:          "#e7e4ed"
    readonly property color primary:     "#c1c7ff"
    readonly property color primaryFg:   "#2436b6"
    readonly property color secondary:   "#c7caf4"
    readonly property color tertiary:    "#ffbe93"
    readonly property color tertiaryFg:  "#973e00"
    readonly property color outline:     "#5e5f70"
    readonly property color error:       "#ffbbb1"
}
