// Generated by matugen — do not edit
import QtQuick

QtObject {
    readonly property color background:  "#4b2b30"
    readonly property color surface:     "#52383c"
    readonly property color surfaceHigh: "#594146"
    readonly property color fg:          "#f9e0e2"
    readonly property color primary:     "#ffb6c6"
    readonly property color primaryFg:   "#a90042"
    readonly property color secondary:   "#ffb6c6"
    readonly property color outline:     "#78585e"
    readonly property color error:       "#ffbbb1"
}
