general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /home/kai/Pictures/Wallpapers/nightsky.png
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(c1c7ff)
    inner_color = rgb(333340)
    font_color = rgb(e7e4ed)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = rgb(ffbe93)
    fail_color = rgb(ffbbb1)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(c7caf4)
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(e7e4ed)
    font_size = 72
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:43200000] date +"%A, %B %d"
    color = rgb(cdccdb)
    font_size = 18
    font_family = JetBrains Mono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}
