-- Generated by matugen — do not edit
return {
  background              = "#4b2b30",
  on_background           = "#f9e0e2",

  surface_container_low   = "#503438",
  surface_container       = "#52383c",
  surface_container_high  = "#594146",
  surface_container_highest = "#634b4f",

  on_surface              = "#f9e0e2",
  on_surface_variant      = "#e7c6ca",

  primary                 = "#ffb6c6",
  on_primary              = "#a90042",
  primary_container       = "#e33b6f",
  on_primary_container    = "#ffffff",

  secondary               = "#ffb6c6",
  on_secondary            = "#8b2943",
  secondary_container     = "#9f4259",

  tertiary                = "#82ee9b",
  on_tertiary             = "#008136",
  tertiary_container      = "#00b556",

  error                   = "#ffbbb1",
  on_error                = "#c60009",
  error_container         = "#e8000f",

  outline                 = "#b7979d",
  outline_variant         = "#78585e",
}
