# vim:ft=kitty

include colors.conf

font_family      CaskaydiaMono Nerd Font
bold_font        CaskaydiaMono Nerd Font Bold
italic_font      CaskaydiaMono Nerd Font Italic
bold_italic_font CaskaydiaMono Nerd Font Bold Italic
font_size        12.0

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

