-- Generated by matugen — do not edit
return {
  background              = "#333340",
  on_background           = "#e7e4ed",

  surface_container_low   = "#3a3a47",
  surface_container       = "#3e3e4a",
  surface_container_high  = "#474751",
  surface_container_highest = "#51515a",

  on_surface              = "#e7e4ed",
  on_surface_variant      = "#cdccdb",

  primary                 = "#c1c7ff",
  on_primary              = "#2436b6",
  primary_container       = "#3c4abd",
  on_primary_container    = "#d7d9ff",

  secondary               = "#c7caf4",
  on_secondary            = "#404679",
  secondary_container     = "#585d8a",

  tertiary                = "#ffbe93",
  on_tertiary             = "#973e00",
  tertiary_container      = "#ae4b00",

  error                   = "#ffbbb1",
  on_error                = "#c60009",
  error_container         = "#e8000f",

  outline                 = "#9f9eae",
  outline_variant         = "#5e5f70",
}
