-- Generated by matugen — do not edit
primaryAlpha   = "{{ colors.primary.default.hex | replace: "#", "" }}"
secondaryAlpha = "{{ colors.secondary.default.hex | replace: "#", "" }}"
surfaceAlpha   = "{{ colors.surface_container_high.default.hex | replace: "#", "" }}"
