// Generated by matugen — do not edit
import QtQuick

QtObject {
    readonly property color background:  "{{colors.background.default.hex}}"
    readonly property color surface:     "{{colors.surface_container.default.hex}}"
    readonly property color surfaceHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color fg:          "{{colors.on_surface.default.hex}}"
    readonly property color primary:     "{{colors.primary.default.hex}}"
    readonly property color primaryFg:   "{{colors.on_primary.default.hex}}"
    readonly property color secondary:   "{{colors.secondary.default.hex}}"
    readonly property color tertiary:    "{{colors.tertiary.default.hex}}"
    readonly property color tertiaryFg:  "{{colors.on_tertiary.default.hex}}"
    readonly property color outline:     "{{colors.outline_variant.default.hex}}"
    readonly property color error:       "{{colors.error.default.hex}}"
}
