vim.cmd("highlight clear")
vim.g.colors_name = "matugen"

local ok, p = pcall(require, "matugen_palette")
if not ok then return end

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Base
hi("Normal",          { fg = p.on_background, bg = p.background })
hi("NormalNC",        { fg = p.on_surface_variant, bg = p.background })
hi("NormalFloat",     { fg = p.on_surface, bg = p.surface_container })
hi("FloatBorder",     { fg = p.outline, bg = p.surface_container })
hi("FloatTitle",      { fg = p.primary, bg = p.surface_container, bold = true })

-- Cursor / line
hi("Cursor",          { fg = p.background, bg = p.primary })
hi("CursorLine",      { bg = p.surface_container_high })
hi("CursorLineNr",    { fg = p.primary, bold = true })
hi("CursorColumn",    { bg = p.surface_container_high })
hi("ColorColumn",     { bg = p.surface_container })
hi("LineNr",          { fg = p.outline })
hi("SignColumn",      { fg = p.outline, bg = p.background })
hi("FoldColumn",      { fg = p.outline, bg = p.background })
hi("Folded",          { fg = p.on_surface_variant, bg = p.surface_container })

-- Selection / search
hi("Visual",          { bg = p.surface_container_highest })
hi("VisualNOS",       { bg = p.surface_container_highest })
hi("Search",          { fg = p.on_primary, bg = p.primary })
hi("IncSearch",       { fg = p.on_primary, bg = p.primary })
hi("CurSearch",       { fg = p.on_primary, bg = p.primary })
hi("Substitute",      { fg = p.on_error, bg = p.error })
hi("MatchParen",      { fg = p.primary, bold = true, underline = true })

-- Status / tab / window
hi("StatusLine",      { fg = p.on_surface, bg = p.surface_container_low })
hi("StatusLineNC",    { fg = p.on_surface_variant, bg = p.surface_container_low })
hi("WinBar",          { fg = p.on_surface, bg = p.surface_container_low })
hi("WinBarNC",        { fg = p.on_surface_variant, bg = p.surface_container_low })
hi("WinSeparator",    { fg = p.outline_variant })
hi("VertSplit",       { fg = p.outline_variant })
hi("TabLine",         { fg = p.on_surface_variant, bg = p.surface_container_low })
hi("TabLineSel",      { fg = p.primary, bg = p.background, bold = true })
hi("TabLineFill",     { bg = p.surface_container_low })

-- Popup menu
hi("Pmenu",           { fg = p.on_surface, bg = p.surface_container_high })
hi("PmenuSel",        { fg = p.on_primary, bg = p.primary })
hi("PmenuSbar",       { bg = p.surface_container_highest })
hi("PmenuThumb",      { bg = p.outline })
hi("PmenuKind",       { fg = p.tertiary, bg = p.surface_container_high })
hi("PmenuKindSel",    { fg = p.on_primary, bg = p.primary })
hi("PmenuExtra",      { fg = p.on_surface_variant, bg = p.surface_container_high })

-- Messages
hi("ErrorMsg",        { fg = p.error })
hi("WarningMsg",      { fg = p.tertiary })
hi("ModeMsg",         { fg = p.on_background, bold = true })
hi("MoreMsg",         { fg = p.primary })
hi("Question",        { fg = p.primary })

-- Misc UI
hi("NonText",         { fg = p.surface_container_highest })
hi("Whitespace",      { fg = p.surface_container_highest })
hi("SpecialKey",      { fg = p.tertiary })
hi("EndOfBuffer",     { fg = p.surface_container_highest })
hi("Title",           { fg = p.primary, bold = true })
hi("Directory",       { fg = p.primary })

-- Diff
hi("DiffAdd",         { fg = p.tertiary, bg = p.surface_container })
hi("DiffChange",      { fg = p.secondary, bg = p.surface_container })
hi("DiffDelete",      { fg = p.error, bg = p.surface_container })
hi("DiffText",        { fg = p.on_background, bg = p.surface_container_high, bold = true })
hi("Added",           { fg = p.tertiary })
hi("Changed",         { fg = p.secondary })
hi("Removed",         { fg = p.error })

-- Syntax
hi("Comment",         { fg = p.outline, italic = true })
hi("Constant",        { fg = p.secondary })
hi("String",          { fg = p.secondary })
hi("Character",       { fg = p.secondary })
hi("Number",          { fg = p.tertiary })
hi("Float",           { fg = p.tertiary })
hi("Boolean",         { fg = p.tertiary })
hi("Identifier",      { fg = p.on_background })
hi("Function",        { fg = p.primary })
hi("Statement",       { fg = p.primary })
hi("Conditional",     { fg = p.primary })
hi("Repeat",          { fg = p.primary })
hi("Label",           { fg = p.primary })
hi("Operator",        { fg = p.on_surface_variant })
hi("Keyword",         { fg = p.primary, italic = true })
hi("Exception",       { fg = p.error })
hi("PreProc",         { fg = p.tertiary })
hi("Include",         { fg = p.primary })
hi("Define",          { fg = p.primary })
hi("Macro",           { fg = p.tertiary })
hi("PreCondit",       { fg = p.tertiary })
hi("Type",            { fg = p.tertiary })
hi("StorageClass",    { fg = p.primary })
hi("Structure",       { fg = p.tertiary })
hi("Typedef",         { fg = p.tertiary })
hi("Special",         { fg = p.tertiary })
hi("SpecialChar",     { fg = p.secondary })
hi("Delimiter",       { fg = p.on_surface_variant })
hi("SpecialComment",  { fg = p.outline, italic = true })
hi("Todo",            { fg = p.on_primary_container, bg = p.primary_container, bold = true })
hi("Error",           { fg = p.error })
hi("Underlined",      { underline = true })

-- Treesitter
hi("@comment",                { link = "Comment" })
hi("@comment.documentation",  { fg = p.outline, italic = true })
hi("@keyword",                { link = "Keyword" })
hi("@keyword.function",       { fg = p.primary, italic = true })
hi("@keyword.return",         { fg = p.primary, italic = true })
hi("@keyword.operator",       { fg = p.primary })
hi("@keyword.import",         { fg = p.primary, italic = true })
hi("@function",               { link = "Function" })
hi("@function.builtin",       { fg = p.primary, bold = true })
hi("@function.call",          { fg = p.primary })
hi("@function.method",        { fg = p.primary })
hi("@function.method.call",   { fg = p.primary })
hi("@constructor",            { fg = p.tertiary })
hi("@variable",               { fg = p.on_background })
hi("@variable.builtin",       { fg = p.tertiary, italic = true })
hi("@variable.parameter",     { fg = p.on_surface_variant })
hi("@variable.member",        { fg = p.on_surface })
hi("@type",                   { link = "Type" })
hi("@type.builtin",           { fg = p.tertiary, italic = true })
hi("@type.definition",        { fg = p.tertiary })
hi("@namespace",              { fg = p.tertiary })
hi("@module",                 { fg = p.tertiary })
hi("@string",                 { link = "String" })
hi("@string.escape",          { fg = p.tertiary })
hi("@string.special",         { fg = p.secondary })
hi("@string.special.url",     { fg = p.secondary, underline = true })
hi("@number",                 { link = "Number" })
hi("@float",                  { link = "Float" })
hi("@boolean",                { link = "Boolean" })
hi("@constant",               { link = "Constant" })
hi("@constant.builtin",       { fg = p.tertiary, bold = true })
hi("@constant.macro",         { fg = p.tertiary })
hi("@operator",               { link = "Operator" })
hi("@punctuation.bracket",    { fg = p.on_surface_variant })
hi("@punctuation.delimiter",  { fg = p.on_surface_variant })
hi("@punctuation.special",    { fg = p.tertiary })
hi("@tag",                    { fg = p.primary })
hi("@tag.attribute",          { fg = p.secondary })
hi("@tag.delimiter",          { fg = p.on_surface_variant })
hi("@attribute",              { fg = p.tertiary })
hi("@diff.plus",              { fg = p.tertiary })
hi("@diff.minus",             { fg = p.error })
hi("@diff.delta",             { fg = p.secondary })

-- Diagnostics
hi("DiagnosticError",              { fg = p.error })
hi("DiagnosticWarn",               { fg = p.tertiary })
hi("DiagnosticInfo",               { fg = p.primary })
hi("DiagnosticHint",               { fg = p.secondary })
hi("DiagnosticUnderlineError",     { undercurl = true, sp = p.error })
hi("DiagnosticUnderlineWarn",      { undercurl = true, sp = p.tertiary })
hi("DiagnosticUnderlineInfo",      { undercurl = true, sp = p.primary })
hi("DiagnosticUnderlineHint",      { undercurl = true, sp = p.secondary })
hi("DiagnosticVirtualTextError",   { fg = p.error, italic = true })
hi("DiagnosticVirtualTextWarn",    { fg = p.tertiary, italic = true })
hi("DiagnosticVirtualTextInfo",    { fg = p.primary, italic = true })
hi("DiagnosticVirtualTextHint",    { fg = p.secondary, italic = true })
hi("DiagnosticSignError",          { fg = p.error })
hi("DiagnosticSignWarn",           { fg = p.tertiary })
hi("DiagnosticSignInfo",           { fg = p.primary })
hi("DiagnosticSignHint",           { fg = p.secondary })
hi("DiagnosticFloatingError",      { fg = p.error })
hi("DiagnosticFloatingWarn",       { fg = p.tertiary })

-- LSP
hi("LspReferenceText",    { bg = p.surface_container_high })
hi("LspReferenceRead",    { bg = p.surface_container_high })
hi("LspReferenceWrite",   { bg = p.surface_container_highest })
hi("LspInlayHint",        { fg = p.outline, italic = true })
hi("LspCodeLens",         { fg = p.outline, italic = true })

-- Git signs
hi("GitSignsAdd",         { fg = p.tertiary })
hi("GitSignsChange",      { fg = p.secondary })
hi("GitSignsDelete",      { fg = p.error })
hi("GitSignsAddNr",       { fg = p.tertiary })
hi("GitSignsChangeNr",    { fg = p.secondary })
hi("GitSignsDeleteNr",    { fg = p.error })
